<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="reciept.aspx.vb" Inherits="reciept" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1>Thank you For your order.</h1>

    <br />
    <br />
    <asp:Label ID="lblDate" runat="server" Text="xx/xx/xxxx"></asp:Label>
<%--    <asp:SqlDataSource ID="SqlDSCart2" runat="server" ConnectionString='<%$ ConnectionStrings:OnlineStoreConnectionString %>' SelectCommand="SELECT * FROM [CustomerInformation]"></asp:SqlDataSource>
    <asp:ListView ID="ListView1" runat="server"DataSourceID="SqlDSCart2">
    <LayoutTemplate>
                                    <div style="float: right; margin: 0 30px 5px 0;">
                                        <asp:Label ID="lblPage" runat="server" Text="" Font-Size="14px"></asp:Label>
                                    </div>
                                    <br />
                                    <table>
                                        <thead>
                                            <tr>
    </asp:ListView>--%>
    
    <br />
    <br />
    <asp:Label ID="lblOrderID" runat="server" Text="Label"></asp:Label>
    <br />
    <asp:Label ID="lblCompanyName" runat="server" Text="Label"></asp:Label>
    <br />
    <asp:Label ID="lblName" runat="server" Text="Label"></asp:Label>
    <br />
    <asp:Label ID="lblAddress" runat="server" Text="Label"></asp:Label>
    <br />
    <asp:Label ID="lblPhone" runat="server" Text="Label"></asp:Label>
      <div class="cart-totals">
          
              <asp:SqlDataSource ID="SqlDSCart1" runat="server"
                  ConnectionString='<%$ ConnectionStrings:OnlineStoreConnectionString %>'
                  SelectCommand=""></asp:SqlDataSource>
          
              <asp:GridView ID="gvCart" runat="server" AutoGenerateColumns="False"
                  DataSourceID="SqlDSCart1" AllowPaging="True" PageSize="3" DataKeyNames="CartID,ProductNo"
                  AutoGenerateDeleteButton="false" AutoGenerateEditButton="false"
                  EmptyDataText="Your Cart is empty.">
                  <Columns>
                      <asp:BoundField DataField="ProductNo" HeaderText="ProductNo" InsertVisible="False" ReadOnly="true"
                          SortExpression="ProductNo" />
                      <asp:BoundField DataField="ProductName" HeaderText="Product Name" InsertVisible="False" ReadOnly="true"
                          SortExpression="ProductName" />
                      <asp:BoundField DataField="Quantity" HeaderText="Quantity"
                          SortExpression="Quantity" />
                      <asp:BoundField DataField="ProductPrice" HeaderText="Price" SortExpression="ProductPrice" InsertVisible="False" ReadOnly="true" />
                      <asp:TemplateField HeaderText="Subtotal">
                          <ItemTemplate>
                              <asp:Label ID="TotalLabel1" runat="server" Text='<%#CalculateSubTotal(Eval("Quantity"), Eval("ProductPrice"))%>'></asp:Label>
                          </ItemTemplate>
                      </asp:TemplateField>
                  </Columns>

              </asp:GridView>
          
    </div>
    <h3>Cart Totals</h3>
            <div class="cart-totals">
                <table class="table">
                    <tr>
                        <th>Cart Subtotal</th>
                        <td>
                            <asp:Label ID="lblSubtotal" runat="server" Text="$0.00"></asp:Label></td>
                    </tr>
                    <tr>
                        <th>Tax</th>
                        <td>
                            <asp:Label ID="lblTax" runat="server" Text="Label"></asp:Label></td>
                    </tr>
                    <tr>
                        <th>Shipping</th>
                        <td>
                            <asp:Label ID="lblShipping" runat="server" Text="Shipping is Free."></asp:Label></td>
                    </tr>
                    <tr>
                        <th><span>Order Total</span></th>
                        <td>
                            <asp:Label ID="lblTotal" runat="server" Text="Label"></asp:Label></td>
                    </tr>
                </table>
                
         <div class="row">
    </div>
    <asp:Label ID="test" runat="server" Text="Label"></asp:Label>
    </div>
    
</asp:Content>

